version: '3.8'
services:
  nest-api:
    container_name: nest-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - .containers/postgres:/var/lib/postgresql/data
  pgadmin:
    links:
      - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - '8080:80'
    volumes:
      - ./.containers/pgadmin:/root/.pgadmin
    env_file:
      - .env
    networks:
      - postgres
volumes:
  postgres:
    name: nest-db
networks:
  postgres:
    driver: bridge
